### ISSUE TITLE
Graceful Failure / Dynatrace token name

### ISSUE THREAD

**Issue by tsteckenborn** [cap-js/telemetry#86]
Currently the plugin seems to crash with an uncaught exception in case of missing information. That should maybe be catched as missing telemetry shouldn't be a show stopper but a warning. Also it seems like the actual api token name required deviates from the readme file (for version 0.0.2).

```
... uncaughtException: Neither metrics_apitoken nor rest_apitoken.token found in Dynatrace credentials\nError: Neither metrics_apitoken nor rest_apitoken.token found in Dynatrace credentials\n    at _getExporter (/home/vcap/deps/0/node_modules/@cap-js/telemetry/lib/metrics/index.js:27:23)\n
```

Yet the documentation describes:

```
Excerpt from example mta.yaml:

requires:
  - name: my-dynatrace-instance
    parameters:
      config:
        tokens:
          - name: ingest_apitoken #> default lookup name, configurable via cds.requires.telemetry.token_name
            scopes:
              - metrics.ingest
```
Which is present in the credentials.

**Comment by sjvans** [comment]
hi @tsteckenborn 

thanks for your feedback!

> That should maybe be catched as missing telemetry shouldn't be a show stopper but a warning.

this is intentional: fail loudly! the developer tried to achieve something and should immediately understand that something isn't right. you can always add `NO_TELEMETRY=true` to your app's env and the plugin will go dead (cf. [Environment variables](https://github.com/cap-js/telemetry/blob/v0.0.2/README.md#environment-variables)), so i wouldn't consider it a show stopper.

for the 0.0.2 readme, you'll need to switch to the respective tag (i.e., https://github.com/cap-js/telemetry/blob/v0.0.2/README.md) as the main branch has already moved on. `ingest_apitoken` will be the default lookup name in 0.0.3, where we also support traces to dynatrace via otel.

best,
sebastian
