### ISSUE TITLE
Sending to Cloud Logging ignores HOST_METRICS_LOG_SYSTEM

### ISSUE THREAD

**Issue by marcsst** [cap-js/telemetry#93]
Flag HOST_METRICS_LOG_SYSTEM seems to only influence the output to console.
System.* metrics are still received in Cloud Logging.

We only need the process.* metrics and receive a lot of data from cloud foundry. 
Host metrics are currently reporting 655 entries per minute that are not even available in the BTP cockpit (more cpu/ram than is assigned to the current instance).

**Comment by sjvans** [comment]
hi @marcsst 

right, `HOST_METRICS_LOG_SYSTEM` is only considered in the console exporter. i'll try to clarify that in the readme.

i'm afraid you'll need to find a different solution, because we only start up @opentelemetry/host-metrics and are not involved any further in case of exporting via otlp... if you find a way to configure @opentelemetry/host-metrics, let me know!

best,
sebastian
